命令稿啟動於 2018年03月16日 上午 11:35:51
]0;~
[32muser@NB1024 [33m~[0m
$ whoami;pwd
user
/home/user
]0;~
[32muser@NB1024 [33m~[0m
$ cd[K[Kg++ -o[K[KLAB1_B[K[K[K[K[K[K[K[K[K[KCD [K[K[Kcd lab1_B
]0;~/lab1_B
[32muser@NB1024 [33m~/lab1_B[0m
$ G==[K[K[Kg++ lab_B.C[Kcb[Kpp
]0;~/lab1_B
[32muser@NB1024 [33m~/lab1_B[0m
$ g++ -o lab_B IAB[K[K[Klab_B.cpp
]0;~/lab1_B
[32muser@NB1024 [33m~/lab1_B[0m
$ ls
1-B.cpp  a.exe	lab_B.cpp  lab_B.exe  lab1  lab1_b.cpp
]0;~/lab1_B
[32muser@NB1024 [33m~/lab1_B[0m
$ ./lab_B
input n = 22
n = 22 11 34 17 52 26 13 40 20 10 5 16 8 4 2 1
]0;~/lab1_B
[32muser@NB1024 [33m~/lab1_B[0m
$ ./LA[K[Klab_B
input n = 66
n = 66 33 100 50 25 76 38 19 58 29 88 44 22 11 34 17 52 26 13 40 20 10 5 16 8 4 2 1
]0;~/lab1_B
[32muser@NB1024 [33m~/lab1_B[0m
$ GIT [K[K[K[Kgit clone https://github.com/Chang-Yu-I[Kl[KLing/iab1[K[K[K[Klab1.git
fatal: destination path 'lab1' already exists and is not an empty directory.
]0;~/lab1_B
[32muser@NB1024 [33m~/lab1_B[0m
$ exit

命令稿已於 2018年03月16日 上午 11:49:16
 完成