命令稿啟動於 2018年03月14日 上午 01:02:07
]0;~/123
[32muser@NB1024 [33m~/123[0m
$ whom[Kami;pwd
user
/home/user/123
]0;~/123
[32muser@NB1024 [33m~/123[0m
$ git config -l
user.email=alice310ch@gmail.com
user.name=Chang-Yu-Ling
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
core.ignorecase=true
]0;~/123
[32muser@NB1024 [33m~/123[0m
$ git clone https://github.com/c[KChang-Yu-LING[K[K[King/lab1.
git
Cloning into 'lab1'...
remote: Counting objects: 3, done.[K
remote: Compressing objects:  50% (1/2)   [Kremote: Compressing objects: 100% (2/2)   [Kremote: Compressing objects: 100% (2/2), done.[K
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0[K
Unpacking objects:  33% (1/3)   Unpacking objects:  66% (2/3)   Unpacking objects: 100% (3/3)   Unpacking objects: 100% (3/3), done.
]0;~/123
[32muser@NB1024 [33m~/123[0m
$ exit

命令稿已於 2018年03月14日 上午 01:09:24
 完成